[dataset]
files_path_root = "/local/scratch/faehnrich/AgroscopeData/LabelledSequences"
original_files_and_labels_path = "/local/scratch/faehnrich/AgroscopeData/LabelledSequencesMerged.xlsx"
train_files_and_labels_path_alpha = "/local/scratch/faehnrich/Labels/Alpha/train_dataset_info.xlsx"
train_files_and_labels_path_alpha_beta = "/local/scratch/faehnrich/Labels/AlphaBeta/train_dataset_info.xlsx"

[spectrogram]
spectrograms_dir = "/local/scratch/faehnrich/Spectrograms"

[model]
alpha = "/home/user/faehnrich/ChiRO/data/DataAlpha/models/Alpha"
beta = "/home/user/faehnrich/ChiRO/data/DataAlpha/models/Beta"
gamma = "/home/user/faehnrich/ChiRO/data/DataAlpha/models/Gamma"