[dataset]
files_path_root = "/cluster/raid/home/f60047174/data/LabelledSequences"
original_files_and_labels_path = "/cluster/raid/home/f60047174/data/LabelledSequencesMerged.xlsx"
train_files_and_labels_path_alpha = "/cluster/raid/home/f60047174/ChiRO/data/Alpha/train_dataset_info.xlsx"
train_files_and_labels_path_beta = "/cluster/raid/home/f60047174/ChiRO/data/Beta/train_dataset_info.xlsx"
train_files_and_labels_path_alpha_beta = "/cluster/raid/home/f60047174/ChiRO/data/AlphaBeta/train_dataset_info.xlsx"

[spectrogram]
spectrograms_dir = "/cluster/raid/home/f60047174/data/spectrograms"

[model]
alpha = "/cluster/raid/home/f60047174/ChiRO/src/models/Alpha"
alpha_beta = "/cluster/raid/home/f60047174/ChiRO/src/models/AlphaBeta"
beta = "/cluster/raid/home/f60047174/src/models/Beta"
gamma = "/cluster/raid/home/f60047174/ChiRO/src/models/Gamma"
detection_model_path = "/cluster/raid/home/f60047174/ChiRO/src/Batdetect2/Net2DFast_UK_same.pth.tar"