[dataset]
files_path_root = "/cluster/raid/home/f60047174/data/LabelledSequences"
original_files_and_labels_path = "/cluster/raid/home/f60047174/data/LabelledSequencesMerged_cleaned_cleaned_cleaned_cleaned.xlsx"
train_files_and_labels_path_alpha = "/cluster/raid/home/f60047174/ChiRO/data/Alpha/train_dataset_info.xlsx"
train_files_and_labels_path_beta = "/cluster/raid/home/f60047174/ChiRO/data/Beta/train_dataset_info.xlsx"
train_files_and_labels_path_alpha_beta = "/cluster/raid/home/f60047174/ChiRO/data/AlphaBeta/train_dataset_info.xlsx"
train_files_and_labels_path_gamma = "/cluster/raid/home/f60047174/ChiRO/data/Gamma/train_dataset_info.xlsx"
validation_files_and_labels_path_alpha = "/cluster/raid/home/f60047174/ChiRO/data/Alpha/val_dataset_info.xlsx"
validation_files_and_labels_path_beta = "/cluster/raid/home/f60047174/ChiRO/data/Beta/val_dataset_info.xlsx"
validation_files_and_labels_path_gamma = "/cluster/raid/home/f60047174/ChiRO/data/Gamma/val_dataset_info.xlsx"

[spectrogram]
spectrograms_dir = "/cluster/raid/home/f60047174/data/spectrograms"

[logs]
runs_dir_alpha = "/cluster/raid/home/f60047174/ChiRO/data/runs/alpha"
runs_dir_beta = "/cluster/raid/home/f60047174/ChiRO/data/runs/beta"
runs_dir_gamma = "/cluster/raid/home/f60047174/ChiRO/data/runs/gamma"

[model]
alpha = "/cluster/raid/home/f60047174/ChiRO/src/models/Alpha"
alpha_beta = "/cluster/raid/home/f60047174/ChiRO/src/models/AlphaBeta"
beta = "/cluster/raid/home/f60047174/src/models/Beta"
gamma = "/cluster/raid/home/f60047174/ChiRO/src/models/Gamma"
pretrained_alphaV3 = "/cluster/raid/home/f60047174/ChiRO/src/Training/AlphaV2SectionDynamicPretrained.pth"
detection_model_path = "/cluster/raid/home/f60047174/ChiRO/src/Batdetect2/Net2DFast_UK_same.pth.tar"