[dataset]
files_path_root = "D:/Bachelorarbeit/AgroscopeData/LabelledSequences"
train_files_and_labels_path = "C:/Users/MartinFaehnrich/Documents/ChiRO/data/DataBeta/dataset_info_min/train_dataset_info.xlsx"
original_files_and_labels_path = "D:/Bachelorarbeit/AgroscopeData/LabelledSequencesMerged.xlsx"

[spectrogram]
spectrograms_dir = "C:/Users/MartinFaehnrich/Documents/ChiRO/data/spectrograms"

[model]
alpha = "C:/Users/MartinFaehnrich/Documents/ChiRO/src/models/Alpha"
alpha_beta = "C:/Users/MartinFaehnrich/Documents/ChiRO/src/models/AlphaBeta"
beta = "C:/Users/MartinFaehnrich/Documents/ChiRO/src/models/Beta"
gamma = "C:/Users/MartinFaehnrich/Documents/ChiRO/src/models/Gamma"